pipeline:
  install:
    image: node:8.5
    commands:
      - git clone https://github.com/chaostreff-flensburg/wiki.git content
      - npm i
  build:
    image: node:8.5
    commands:
      - npm run parse
      - npm run generate
  stage:
    image: node:8.5
    commands:
      - cp -a ./dist/. /var/www/devrakede/
    volumes:
      - /var/www/devrakede:/var/www/devrakede

branches: [master, dev, feature/*, bug/*, hotfix/*]
